### ISSUE TITLE
cannot import

### ISSUE THREAD

**Issue by lmanzurv** [boscoh/sassin#2]
Instruction @import base.sass does not work inside home.sass. Raises the following error IOError: Error: @import 'base.sass' not found at :2

static structure is as follows:

static
-- application
---- sass
------ base.sass
------ home.sass

**Comment by boscoh** [comment]
I need more information. For instance, where are you running sassin? 

Import loads only the given filename, so sassin must be run from the same directory as the import.

**Comment by lmanzurv** [comment]
sassin is being run from inside a django application. Isn't it better to check the existence of the file from inside the directory of the one doing the import? Haven't tried it but it should be something like

os.path.isfile(os.path.join(os.path.dirname(source_fname), import_fname))

**Comment by boscoh** [comment]
sounds like a good fix for your problem. send a pull-request and i'll patch it in.

**Comment by lmanzurv** [comment]
Pull request ready
