### ISSUE TITLE
comments being deleted

### ISSUE THREAD

**Issue by lmanzurv** [boscoh/sassin#3]
Comments written as /\* Comment */ get deleted and only maintains the ending */

For example:

*/;
*/;
*/;
.content-row{height:100%}

**Comment by boscoh** [comment]
What is your input to get that output?

**Comment by lmanzurv** [comment]
For example:

/\* Colors */
$white-color: #ffffff;

/\* Mixins */
=perspective($value)
    -webkit-perspective: $value
    -moz-perspective: $value
    -o-perspective: $value
    -ms-perspective: $value
    perspective: $value

Those are valid comments in sass according to http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments

**Comment by boscoh** [comment]
It would help greatly if you could provide an exact piece of input that reproduces your bug (as per standard practice), with the exact commands. 

For instance, I have made `try.sass`:

```
/*  haha */
/*  no */
/*  nono */
.content-row
  height: 100%
```

and using:

```
>>> sassin try.sass
```

I get `try.scss`: 

```
/*  haha */
/*  no */
/*  nono */
.content-row {
  height: 100%; }

```

**Comment by lmanzurv** [comment]
A base.sass file like the next

/\* Variables */
$body-font: 'Roboto', sans-serif
$heading-font-bold: 'Walkway Bold', sans-serif
$heading-font-semibold: 'Walkway Semibold', sans-serif

/\* Colors */
$majolica-dark-color: #163444
$light-gray-color: #f2f2f2
$gray-color: #cccccc
$sunshine-color: #ffce00
$white-color: #ffffff
$olive-color: #cece00
$dark-olive-color: #bcb700
$coral-color: #ff2c5e
$dark-coral-color: #d82558
$beige-color: #faf8bb
$dark-beige-color: #fff992

Outputs the following (different from what was outputting at first, but nevertheless weird):

/\* Variables */
$body-font: 'Roboto', sans-serif;
$heading-font-bold: 'Walkway Bold', sans-serif;
$heading-font-semibold: 'Walkway Semibold', sans-serif;
// Colors;
$majolica-dark-color: #163444;
$light-gray-color: #f2f2f2;
$gray-color: #cccccc;
$sunshine-color: #ffce00;
$white-color: #ffffff;
$olive-color: #cece00;
$dark-olive-color: #bcb700;
$coral-color: #ff2c5e;
$dark-coral-color: #d82558;
$beige-color: #faf8bb;
$dark-beige-color: #fff992;

**Comment by boscoh** [comment]
When I run `sassin` on the the text, which I saved as `try.sass`, I get `try.scss`:

```
/* Variables */
$body-font: 'Roboto', sans-serif;
$heading-font-bold: 'Walkway Bold', sans-serif;
$heading-font-semibold: 'Walkway Semibold', sans-serif;
/* Colors */
$majolica-dark-color: #163444;
$light-gray-color: #f2f2f2;
$gray-color: #cccccc;
$sunshine-color: #ffce00;
$white-color: #ffffff;
$olive-color: #cece00;
$dark-olive-color: #bcb700;
$coral-color: #ff2c5e;
$dark-coral-color: #d82558;
$beige-color: #faf8bb;
$dark-beige-color: #fff992;
```

which looks okay to me.

I can't seem to reproduce your problem. Is it a pyscss problem? Have you installed the latest sassin?

**Comment by lmanzurv** [comment]
Ok, just checked, the output is correct, pySCSS is removing them.
